"""Add new column

Revision ID: 0ffad1c15421
Revises: e0f0c1d2e3f4
Create Date: 2026-01-27 11:45:50.481343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0ffad1c15421'
down_revision: Union[str, None] = 'e0f0c1d2e3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('document_collection_name'), table_name='document')
    op.drop_index(op.f('document_name'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('chatidtag_id'), table_name='chatidtag')
    op.drop_table('chatidtag')
    op.alter_column('api_key', 'user_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'api_key', type_='foreignkey')
    op.alter_column('auth', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('auth', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('auth', 'active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=True)
    op.drop_index(op.f('auth_id'), table_name='auth')
    op.create_unique_constraint(None, 'auth', ['id'])
    op.drop_index(op.f('ix_channel_file_channel_id'), table_name='channel_file')
    op.drop_index(op.f('ix_channel_file_file_id'), table_name='channel_file')
    op.drop_index(op.f('ix_channel_file_user_id'), table_name='channel_file')
    op.create_unique_constraint(None, 'channel_file', ['id'])
    op.alter_column('channel_member', 'joined_at',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(None, 'channel_webhook', type_='foreignkey')
    op.alter_column('chat', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('chat', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('chat', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('chat', 'updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('chat', 'share_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('chat', 'archived',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=True)
    op.alter_column('chat', 'meta',
               existing_type=sqlite.JSON(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))
    op.drop_index(op.f('chat_id'), table_name='chat')
    op.drop_index(op.f('chat_share_id'), table_name='chat')
    op.create_unique_constraint(None, 'chat', ['id'])
    op.create_unique_constraint(None, 'chat', ['share_id'])
    op.drop_index(op.f('ix_chat_file_chat_id'), table_name='chat_file')
    op.drop_index(op.f('ix_chat_file_file_id'), table_name='chat_file')
    op.drop_index(op.f('ix_chat_file_message_id'), table_name='chat_file')
    op.drop_index(op.f('ix_chat_file_user_id'), table_name='chat_file')
    op.create_unique_constraint(None, 'chat_file', ['id'])
    op.alter_column('email_verification', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('email_verification', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('email_verification', 'code_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('email_verification', 'attempts_remaining',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('email_verification', 'expires_at',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('email_verification', 'last_sent_at',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('email_verification', 'intended_role',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'user'"))
    op.alter_column('email_verification', 'created_at',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('email_verification', 'disable_signup_after_verify',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(false)'))
    op.drop_index(op.f('email_verification_email_idx'), table_name='email_verification')
    op.drop_index(op.f('email_verification_token_hash_idx'), table_name='email_verification')
    op.drop_index(op.f('email_verification_user_id_idx'), table_name='email_verification')
    op.create_index(op.f('ix_email_verification_email'), 'email_verification', ['email'], unique=False)
    op.create_index(op.f('ix_email_verification_user_id'), 'email_verification', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'email_verification', ['id'])
    op.alter_column('feedback', 'created_at',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('feedback', 'updated_at',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_unique_constraint(None, 'feedback', ['id'])
    op.alter_column('file', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('file', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('file', 'filename',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('file', 'created_at',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.drop_index(op.f('file_id'), table_name='file')
    op.create_unique_constraint(None, 'file', ['id'])
    op.alter_column('folder', 'user_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('folder', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('folder', 'is_expanded',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('folder', 'created_at',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('folder', 'updated_at',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_unique_constraint(None, 'folder', ['id'])
    op.alter_column('function', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('function', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('function', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('function', 'type',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('function', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('function', 'meta',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('function', 'is_active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=True)
    op.alter_column('function', 'is_global',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=True)
    op.alter_column('function', 'updated_at',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('function', 'created_at',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.drop_index(op.f('function_id'), table_name='function')
    op.create_unique_constraint(None, 'function', ['id'])
    op.drop_constraint(op.f('uq_group_member_group_user'), 'group_member', type_='unique')
    op.drop_constraint(None, 'group_member', type_='foreignkey')
    op.alter_column('knowledge', 'user_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('knowledge', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('knowledge', 'created_at',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_unique_constraint(None, 'knowledge', ['id'])
    op.drop_column('knowledge', 'data')
    op.drop_index(op.f('ix_knowledge_file_file_id'), table_name='knowledge_file')
    op.drop_index(op.f('ix_knowledge_file_knowledge_id'), table_name='knowledge_file')
    op.drop_index(op.f('ix_knowledge_file_user_id'), table_name='knowledge_file')
    op.create_unique_constraint(None, 'knowledge_file', ['id'])
    op.alter_column('memory', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('memory', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('memory', 'updated_at',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('memory', 'created_at',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.drop_index(op.f('memory_id'), table_name='memory')
    op.create_unique_constraint(None, 'memory', ['id'])
    op.alter_column('message_reaction', 'user_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('message_reaction', 'message_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('message_reaction', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('model', 'user_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('model', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('model', 'params',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('model', 'meta',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('model', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('model', 'updated_at',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('model', 'created_at',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.drop_index(op.f('model_id'), table_name='model')
    op.create_unique_constraint(None, 'model', ['id'])
    op.drop_constraint(None, 'oauth_session', type_='foreignkey')
    op.alter_column('payment_event', 'created_at',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index(op.f('payment_event_payment_id_idx'), table_name='payment_event')
    op.create_index(op.f('ix_payment_event_payment_id'), 'payment_event', ['payment_id'], unique=False)
    op.alter_column('payment_transaction', 'user_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('payment_transaction', 'created_at',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('payment_transaction', 'updated_at',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index(op.f('payment_transaction_invoice_idx'), table_name='payment_transaction')
    op.drop_index(op.f('payment_transaction_payment_id_idx'), table_name='payment_transaction')
    op.drop_index(op.f('payment_transaction_user_id_idx'), table_name='payment_transaction')
    op.create_index(op.f('ix_payment_transaction_merchant_invoice_number'), 'payment_transaction', ['merchant_invoice_number'], unique=False)
    op.create_index(op.f('ix_payment_transaction_payment_id'), 'payment_transaction', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_transaction_user_id'), 'payment_transaction', ['user_id'], unique=False)
    op.alter_column('prompt', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('prompt', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('prompt', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('prompt', 'timestamp',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.drop_index(op.f('prompt_command'), table_name='prompt')
    op.drop_column('prompt', 'id')
    op.alter_column('tag', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('user_id_idx'), table_name='tag')
    op.drop_index(op.f('token_budget_user_id_idx'), table_name='token_budget')
    op.drop_constraint(op.f('token_budget_user_id_uq'), 'token_budget', type_='unique')
    op.create_index(op.f('ix_token_budget_user_id'), 'token_budget', ['user_id'], unique=True)
    op.drop_index(op.f('token_usage_event_created_at_idx'), table_name='token_usage_event')
    op.drop_index(op.f('token_usage_event_request_id_idx'), table_name='token_usage_event')
    op.drop_constraint(op.f('token_usage_event_request_id_uq'), 'token_usage_event', type_='unique')
    op.drop_index(op.f('token_usage_event_user_id_idx'), table_name='token_usage_event')
    op.create_index(op.f('ix_token_usage_event_created_at'), 'token_usage_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_token_usage_event_request_id'), 'token_usage_event', ['request_id'], unique=True)
    op.create_index(op.f('ix_token_usage_event_user_id'), 'token_usage_event', ['user_id'], unique=False)
    op.drop_index(op.f('token_window_aggregate_user_id_idx'), table_name='token_window_aggregate')
    op.drop_index(op.f('token_window_aggregate_user_window_idx'), table_name='token_window_aggregate')
    op.create_index(op.f('ix_token_window_aggregate_user_id'), 'token_window_aggregate', ['user_id'], unique=False)
    op.alter_column('tool', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tool', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('tool', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tool', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tool', 'specs',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tool', 'meta',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tool', 'updated_at',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('tool', 'created_at',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.drop_index(op.f('tool_id'), table_name='tool')
    op.create_unique_constraint(None, 'tool', ['id'])
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'profile_image_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'last_active_at',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('user', 'updated_at',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.drop_index(op.f('user_id'), table_name='user')
    op.drop_column('user', 'email_verification_sent_at')
    op.drop_column('user', 'email_verified_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verified_at', sa.INTEGER(), nullable=True))
    op.add_column('user', sa.Column('email_verification_sent_at', sa.INTEGER(), nullable=True))
    op.create_index(op.f('user_id'), 'user', ['id'], unique=1)
    op.alter_column('user', 'created_at',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'last_active_at',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'profile_image_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'tool', type_='unique')
    op.create_index(op.f('tool_id'), 'tool', ['id'], unique=1)
    op.alter_column('tool', 'created_at',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('tool', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('tool', 'meta',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tool', 'specs',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tool', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tool', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tool', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('tool', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_token_window_aggregate_user_id'), table_name='token_window_aggregate')
    op.create_index(op.f('token_window_aggregate_user_window_idx'), 'token_window_aggregate', ['user_id', 'window_start'], unique=False)
    op.create_index(op.f('token_window_aggregate_user_id_idx'), 'token_window_aggregate', ['user_id'], unique=False)
    op.drop_index(op.f('ix_token_usage_event_user_id'), table_name='token_usage_event')
    op.drop_index(op.f('ix_token_usage_event_request_id'), table_name='token_usage_event')
    op.drop_index(op.f('ix_token_usage_event_created_at'), table_name='token_usage_event')
    op.create_index(op.f('token_usage_event_user_id_idx'), 'token_usage_event', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('token_usage_event_request_id_uq'), 'token_usage_event', ['request_id'])
    op.create_index(op.f('token_usage_event_request_id_idx'), 'token_usage_event', ['request_id'], unique=False)
    op.create_index(op.f('token_usage_event_created_at_idx'), 'token_usage_event', ['created_at'], unique=False)
    op.drop_index(op.f('ix_token_budget_user_id'), table_name='token_budget')
    op.create_unique_constraint(op.f('token_budget_user_id_uq'), 'token_budget', ['user_id'])
    op.create_index(op.f('token_budget_user_id_idx'), 'token_budget', ['user_id'], unique=False)
    op.create_index(op.f('user_id_idx'), 'tag', ['user_id'], unique=False)
    op.alter_column('tag', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('prompt', sa.Column('id', sa.INTEGER(), nullable=False))
    op.create_index(op.f('prompt_command'), 'prompt', ['command'], unique=1)
    op.alter_column('prompt', 'timestamp',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('prompt', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('prompt', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('prompt', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_payment_transaction_user_id'), table_name='payment_transaction')
    op.drop_index(op.f('ix_payment_transaction_payment_id'), table_name='payment_transaction')
    op.drop_index(op.f('ix_payment_transaction_merchant_invoice_number'), table_name='payment_transaction')
    op.create_index(op.f('payment_transaction_user_id_idx'), 'payment_transaction', ['user_id'], unique=False)
    op.create_index(op.f('payment_transaction_payment_id_idx'), 'payment_transaction', ['payment_id'], unique=False)
    op.create_index(op.f('payment_transaction_invoice_idx'), 'payment_transaction', ['merchant_invoice_number'], unique=False)
    op.alter_column('payment_transaction', 'updated_at',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('payment_transaction', 'created_at',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('payment_transaction', 'user_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_payment_event_payment_id'), table_name='payment_event')
    op.create_index(op.f('payment_event_payment_id_idx'), 'payment_event', ['payment_id'], unique=False)
    op.alter_column('payment_event', 'created_at',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_foreign_key(None, 'oauth_session', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'model', type_='unique')
    op.create_index(op.f('model_id'), 'model', ['id'], unique=1)
    op.alter_column('model', 'created_at',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('model', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('model', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('model', 'meta',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('model', 'params',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('model', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('model', 'user_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('message_reaction', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('message_reaction', 'message_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('message_reaction', 'user_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'memory', type_='unique')
    op.create_index(op.f('memory_id'), 'memory', ['id'], unique=1)
    op.alter_column('memory', 'created_at',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('memory', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('memory', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('memory', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'knowledge_file', type_='unique')
    op.create_index(op.f('ix_knowledge_file_user_id'), 'knowledge_file', ['user_id'], unique=False)
    op.create_index(op.f('ix_knowledge_file_knowledge_id'), 'knowledge_file', ['knowledge_id'], unique=False)
    op.create_index(op.f('ix_knowledge_file_file_id'), 'knowledge_file', ['file_id'], unique=False)
    op.add_column('knowledge', sa.Column('data', sqlite.JSON(), nullable=True))
    op.drop_constraint(None, 'knowledge', type_='unique')
    op.alter_column('knowledge', 'created_at',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('knowledge', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('knowledge', 'user_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_foreign_key(None, 'group_member', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_group_member_group_user'), 'group_member', ['group_id', 'user_id'])
    op.drop_constraint(None, 'function', type_='unique')
    op.create_index(op.f('function_id'), 'function', ['id'], unique=1)
    op.alter_column('function', 'created_at',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('function', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('function', 'is_global',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('function', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('function', 'meta',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('function', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('function', 'type',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('function', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('function', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('function', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'folder', type_='unique')
    op.alter_column('folder', 'updated_at',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('folder', 'created_at',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('folder', 'is_expanded',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('folder', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('folder', 'user_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'file', type_='unique')
    op.create_index(op.f('file_id'), 'file', ['id'], unique=1)
    op.alter_column('file', 'created_at',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('file', 'filename',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('file', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('file', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'feedback', type_='unique')
    op.alter_column('feedback', 'updated_at',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('feedback', 'created_at',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'email_verification', type_='unique')
    op.drop_index(op.f('ix_email_verification_user_id'), table_name='email_verification')
    op.drop_index(op.f('ix_email_verification_email'), table_name='email_verification')
    op.create_index(op.f('email_verification_user_id_idx'), 'email_verification', ['user_id'], unique=False)
    op.create_index(op.f('email_verification_token_hash_idx'), 'email_verification', ['verification_token_hash'], unique=False)
    op.create_index(op.f('email_verification_email_idx'), 'email_verification', ['email'], unique=False)
    op.alter_column('email_verification', 'disable_signup_after_verify',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(false)'))
    op.alter_column('email_verification', 'created_at',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('email_verification', 'intended_role',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'user'"))
    op.alter_column('email_verification', 'last_sent_at',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('email_verification', 'expires_at',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('email_verification', 'attempts_remaining',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('email_verification', 'code_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('email_verification', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('email_verification', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'chat_file', type_='unique')
    op.create_index(op.f('ix_chat_file_user_id'), 'chat_file', ['user_id'], unique=False)
    op.create_index(op.f('ix_chat_file_message_id'), 'chat_file', ['message_id'], unique=False)
    op.create_index(op.f('ix_chat_file_file_id'), 'chat_file', ['file_id'], unique=False)
    op.create_index(op.f('ix_chat_file_chat_id'), 'chat_file', ['chat_id'], unique=False)
    op.drop_constraint(None, 'chat', type_='unique')
    op.drop_constraint(None, 'chat', type_='unique')
    op.create_index(op.f('chat_share_id'), 'chat', ['share_id'], unique=1)
    op.create_index(op.f('chat_id'), 'chat', ['id'], unique=1)
    op.alter_column('chat', 'meta',
               existing_type=sqlite.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))
    op.alter_column('chat', 'archived',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('chat', 'share_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('chat', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=sa.DATETIME(),
               nullable=False)
    op.alter_column('chat', 'created_at',
               existing_type=sa.BigInteger(),
               type_=sa.DATETIME(),
               nullable=False)
    op.alter_column('chat', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('chat', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key(None, 'channel_webhook', 'channel', ['channel_id'], ['id'], ondelete='CASCADE')
    op.alter_column('channel_member', 'joined_at',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'channel_file', type_='unique')
    op.create_index(op.f('ix_channel_file_user_id'), 'channel_file', ['user_id'], unique=False)
    op.create_index(op.f('ix_channel_file_file_id'), 'channel_file', ['file_id'], unique=False)
    op.create_index(op.f('ix_channel_file_channel_id'), 'channel_file', ['channel_id'], unique=False)
    op.drop_constraint(None, 'auth', type_='unique')
    op.create_index(op.f('auth_id'), 'auth', ['id'], unique=1)
    op.alter_column('auth', 'active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('auth', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('auth', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key(None, 'api_key', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('api_key', 'user_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_table('chatidtag',
    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('tag_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('timestamp', sa.INTEGER(), nullable=False)
    )
    op.create_index(op.f('chatidtag_id'), 'chatidtag', ['id'], unique=1)
    op.create_table('document',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('collection_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('filename', sa.TEXT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('timestamp', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('document_name'), 'document', ['name'], unique=1)
    op.create_index(op.f('document_collection_name'), 'document', ['collection_name'], unique=1)
    # ### end Alembic commands ###
